apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: logging-cluster
  namespace: kubeprod
spec:
  general:
    version: "2.7.0"
    httpPort: 9200
    vendor: opensearch
    serviceName: logging-cluster
  dashboards:
    version: "2.7.0"
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "10Gi"
      jvm: -Xmx1024M -Xms1024M
      nodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"