apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  general:
    version: "2.7.0"
    httpPort: 9200
    vendor: opensearch
    serviceName: opensearch
  dashboards:
    version: "2.7.0"
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "100m"
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hostname
                    operator: In
                    values:
                      - oke-cp2kyidphiq-njtddg7kezq-snkqjdqu6iq-3
  nodePools:
    - component: masters
      replicas: 2
      diskSize: "10Gi"
      jvm: -Xmx1024M -Xms1024M
      nodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
        hostPath:
          path: "/var/opensearch"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hostname
                    operator: In
                    values:
                      - oke-cp2kyidphiq-njtddg7kezq-snkqjdqu6iq-0
                      - oke-cp2kyidphiq-njtddg7kezq-snkqjdqu6iq-1
                      - oke-cp2kyidphiq-njtddg7kezq-snkqjdqu6iq-2
